### ISSUE TITLE
compile error with clang-3.7 sys-devel/.../instrument.cpp:159:59: error: cannot convert 'const llvm::DataLayout' to 'const llvm::DataLayout*' in initialization

### ISSUE THREAD

**Issue by toralf** [losalamos/Byfl#13]
/var/tmp/portage/sys-devel/byfl-1.3/work/byfl-1.3/lib/bytesflops/instrument.cpp: In member function 'void bytesflops_pass::BytesFlops::instrument_load_store(llvm::Module*, llvm::StringRef, llvm::BasicBlock::iterator&, llvm::LLVMContext&, llvm::BasicBlock::iterator&, int&)':
/var/tmp/portage/sys-devel/byfl-1.3/work/byfl-1.3/lib/bytesflops/instrument.cpp:159:59: error: cannot convert 'const llvm::DataLayout' to 'const llvm::DataLayout*' in initialization
     const DataLayout* target_data = module->getDataLayout();

https://bugs.gentoo.org/show_bug.cgi?id=559872

**Comment by spakin** [comment]
There is now an [llvm-3.7 branch of Byfl](https://github.com/losalamos/Byfl/tree/llvm-3.7) and a corresponding [Byfl release](https://github.com/losalamos/Byfl/releases/tag/v1.4-llvm-3.7.0) that are compatible with LLVM/Clang 3.7.*x*.  I believe that should solve your issue, at least here on the upstream side.  Please re-open the issue if it does not.
